
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 82, in <module>
    navigate(ship, find_best_position(ship))
  File "MyBot.py", line 65, in navigate
    long_targets[ship.id] = a_star(ship.position, target)
  File "MyBot.py", line 39, in a_star
    came_from[start] = none
NameError: name 'none' is not defined

