
Turn 3
================================================================
warning: entity 0 was directed to use 5 halite to move north, but only 0 halite was available
At command 1 of 2:
>>> 1   m 0 n
    2   g


Turn 5
================================================================
warning: entity 0 was directed to use 11 halite to move north, but only 10 halite was available
At command 1 of 3:
>>> 1   m 0 n
    2   m 2 n
    3   g

warning: entity 2 was directed to use 3 halite to move north, but only 0 halite was available
At command 2 of 3:
    1   m 0 n
>>> 2   m 2 n
    3   g


Turn 7
================================================================
warning: entity 0 was directed to use 43 halite to move north, but only 32 halite was available
At command 1 of 4:
>>> 1   m 0 n
    2   m 2 n
    3   m 4 n

warning: entity 4 was directed to use 2 halite to move north, but only 0 halite was available
At command 3 of 4:
    1   m 0 n
    2   m 2 n
>>> 3   m 4 n
    4   g

warning: owned entities 2, 0 collided on cell (8, 13) as the result of moves on this turn
At command 2 of 4:
    1   m 0 n
>>> 2   m 2 n
    3   m 4 n
    4   g


Turn 8
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 88, in <module>
    set_long_target(ship)
  File "MyBot.py", line 60, in set_long_target
    if not has_arrival_conflict(ship, cell.position):
  File "MyBot.py", line 26, in has_arrival_conflict
    conflict_ship = me.get_ship(ship_id)
  File "C:\Users\justi\Documents\GitHub\ais-halite\hlt\player.py", line 22, in get_ship
    return self._ships[ship_id]
KeyError: 2

