
Turn 1
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 95, in <module>
    players = game.players.values().pop(game.my_id)
AttributeError: 'dict_values' object has no attrib
